### ISSUE TITLE
Using as a library

### ISSUE THREAD

**Issue by Oreolek** [sequitur/undularity#6]
Consider this usage: I want to use a Javascript library depending on jQuery.
There is no npm alternative.

So I must include _another_ copy of jQuery in `<script>` tags and reference to it as `self.jQuery`.
I don't want to include jQuery twice, so there are two options:
1. Rewrite every library I want to use for npm and browserify
2. Rewrite Raconteur as a simple JS library, as Undum works

Is second option possible and how?

**Comment by sequitur** [comment]
Anything is possible, but not all things I can help you with; and this is certainly not a Raconteur bug or issue.
